### ISSUE TITLE
DMS Special characters problem on migration and upload

### ISSUE THREAD

**Issue by norbertbede** [logilite/logilite-DMS#12]
**issue when failed upload on 2 use cases**
1. migrate attachement to DMS
2. upload regular content

**ERROR LOG**
```
    org.adempiere.exceptions.AdempiereException: FileName: Snímka.PNG : Invalid File Name.
	at com.logilite.dms.util.Utils.validateFileName(Utils.java:615)
	at com.logilite.dms.storage.RelationalContentManager.addFile(RelationalContentManager.java:276)
	at com.logilite.dms.DMS.addFile(DMS.java:524)
	at com.logilite.dms.DMS.addFile(DMS.java:519)
	at com.logilite.dms.process.MigrateAttachmentToDMS.doIt(MigrateAttachmentToDMS.java:76)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:256)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:164)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:173)
```

**examples failed**
- Obrázok1.PNG  image1.png
-  Snímka.PNG -≥ shot.png
- stiahnuť.png -≥ download.png
- plán.PNG

I would say sanitize, or slugify inputed files and store it on disk with safe chars can be affordable (or store it as hash like alfreso)

_ps. my uplad on 30k stopd approx 150x then i download the attachement, rename, upload and continue_

**Comment by sbhimani12** [comment]
[ bc6b557 ] Code Committed: Allow Multiple Language Characters except special characters like  \ " * : ? \ / ^ < > { } |
